columns:
  dteday: datetime64[ns]
  season: object
  yr: object
  mnth: object
  hr: int
  holiday: object
  weekday: object
  workingday: object
  weathersit: object
  temp: float
  atemp: float
  hum: float
  windspeed: float
  casual: int
  registered: int
  cnt: int

numerical_columns:
  - hr
  - temp
  - atemp
  - hum
  - windspeed
  - casual
  - registered
  - cnt

categorical_columns:
  - dteday
  - season
  - yr
  - mnth
  - holiday
  - weekday
  - workingday
  - weathersit

target_column: cnt

drop_col: dteday


