# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bikesharing324

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_57040e9126874771b0b8fc4073db1d90 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6760eecc5a0d43469977d8758311c211 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_57040e9126874771b0b8fc4073db1d90 }}/bike:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bikesharing324'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_14a2cdb9425e4aeaa383fbe81d4c02f0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_57040e9126874771b0b8fc4073db1d90 }}/bike:${{ github.sha }}'