# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bike21324

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4a74c0c15a3744ae8c41ec52aa891ad5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae8b57ab8e534597b7b02d503a88206d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4a74c0c15a3744ae8c41ec52aa891ad5 }}/ashu1407/bikesharingapp1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bike21324'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7be185c95cbc433d895f00dd5b4983ac }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4a74c0c15a3744ae8c41ec52aa891ad5 }}/ashu1407/bikesharingapp1:${{ github.sha }}'